//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace JCILVendorPortal.Serv_Vendor {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_NAV_Vendor_Binding", Namespace="urn:microsoft-dynamics-schemas/page/ws_nav_vendor")]
    public partial class WS_NAV_Vendor_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReadOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadByRecIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsUpdatedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRecIdFromKeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_NAV_Vendor_Service() {
            this.Url = global::JCILVendorPortal.Properties.Settings.Default.JCILVendorPortal_Serv_Vendor_WS_NAV_Vendor_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReadCompletedEventHandler ReadCompleted;
        
        /// <remarks/>
        public event ReadByRecIdCompletedEventHandler ReadByRecIdCompleted;
        
        /// <remarks/>
        public event ReadMultipleCompletedEventHandler ReadMultipleCompleted;
        
        /// <remarks/>
        public event IsUpdatedCompletedEventHandler IsUpdatedCompleted;
        
        /// <remarks/>
        public event GetRecIdFromKeyCompletedEventHandler GetRecIdFromKeyCompleted;
        
        /// <remarks/>
        public event CreateCompletedEventHandler CreateCompleted;
        
        /// <remarks/>
        public event CreateMultipleCompletedEventHandler CreateMultipleCompleted;
        
        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;
        
        /// <remarks/>
        public event UpdateMultipleCompletedEventHandler UpdateMultipleCompleted;
        
        /// <remarks/>
        public event DeleteCompletedEventHandler DeleteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/ws_nav_vendor:Read", RequestNamespace="urn:microsoft-dynamics-schemas/page/ws_nav_vendor", ResponseElementName="Read_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/ws_nav_vendor", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("WS_NAV_Vendor")]
        public WS_NAV_Vendor Read(string No) {
            object[] results = this.Invoke("Read", new object[] {
                        No});
            return ((WS_NAV_Vendor)(results[0]));
        }
        
        /// <remarks/>
        public void ReadAsync(string No) {
            this.ReadAsync(No, null);
        }
        
        /// <remarks/>
        public void ReadAsync(string No, object userState) {
            if ((this.ReadOperationCompleted == null)) {
                this.ReadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadOperationCompleted);
            }
            this.InvokeAsync("Read", new object[] {
                        No}, this.ReadOperationCompleted, userState);
        }
        
        private void OnReadOperationCompleted(object arg) {
            if ((this.ReadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadCompleted(this, new ReadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/ws_nav_vendor:ReadByRecId", RequestNamespace="urn:microsoft-dynamics-schemas/page/ws_nav_vendor", ResponseElementName="ReadByRecId_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/ws_nav_vendor", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("WS_NAV_Vendor")]
        public WS_NAV_Vendor ReadByRecId(string recId) {
            object[] results = this.Invoke("ReadByRecId", new object[] {
                        recId});
            return ((WS_NAV_Vendor)(results[0]));
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId) {
            this.ReadByRecIdAsync(recId, null);
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId, object userState) {
            if ((this.ReadByRecIdOperationCompleted == null)) {
                this.ReadByRecIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadByRecIdOperationCompleted);
            }
            this.InvokeAsync("ReadByRecId", new object[] {
                        recId}, this.ReadByRecIdOperationCompleted, userState);
        }
        
        private void OnReadByRecIdOperationCompleted(object arg) {
            if ((this.ReadByRecIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadByRecIdCompleted(this, new ReadByRecIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/ws_nav_vendor:ReadMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/ws_nav_vendor", ResponseElementName="ReadMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/ws_nav_vendor", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public WS_NAV_Vendor[] ReadMultiple([System.Xml.Serialization.XmlElementAttribute("filter")] WS_NAV_Vendor_Filter[] filter, string bookmarkKey, int setSize) {
            object[] results = this.Invoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize});
            return ((WS_NAV_Vendor[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(WS_NAV_Vendor_Filter[] filter, string bookmarkKey, int setSize) {
            this.ReadMultipleAsync(filter, bookmarkKey, setSize, null);
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(WS_NAV_Vendor_Filter[] filter, string bookmarkKey, int setSize, object userState) {
            if ((this.ReadMultipleOperationCompleted == null)) {
                this.ReadMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadMultipleOperationCompleted);
            }
            this.InvokeAsync("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize}, this.ReadMultipleOperationCompleted, userState);
        }
        
        private void OnReadMultipleOperationCompleted(object arg) {
            if ((this.ReadMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadMultipleCompleted(this, new ReadMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/ws_nav_vendor:IsUpdated", RequestNamespace="urn:microsoft-dynamics-schemas/page/ws_nav_vendor", ResponseElementName="IsUpdated_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/ws_nav_vendor", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")]
        public bool IsUpdated(string Key) {
            object[] results = this.Invoke("IsUpdated", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key) {
            this.IsUpdatedAsync(Key, null);
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key, object userState) {
            if ((this.IsUpdatedOperationCompleted == null)) {
                this.IsUpdatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsUpdatedOperationCompleted);
            }
            this.InvokeAsync("IsUpdated", new object[] {
                        Key}, this.IsUpdatedOperationCompleted, userState);
        }
        
        private void OnIsUpdatedOperationCompleted(object arg) {
            if ((this.IsUpdatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsUpdatedCompleted(this, new IsUpdatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/ws_nav_vendor:GetRecIdFromKey", RequestNamespace="urn:microsoft-dynamics-schemas/page/ws_nav_vendor", ResponseElementName="GetRecIdFromKey_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/ws_nav_vendor", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")]
        public string GetRecIdFromKey(string Key) {
            object[] results = this.Invoke("GetRecIdFromKey", new object[] {
                        Key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key) {
            this.GetRecIdFromKeyAsync(Key, null);
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key, object userState) {
            if ((this.GetRecIdFromKeyOperationCompleted == null)) {
                this.GetRecIdFromKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRecIdFromKeyOperationCompleted);
            }
            this.InvokeAsync("GetRecIdFromKey", new object[] {
                        Key}, this.GetRecIdFromKeyOperationCompleted, userState);
        }
        
        private void OnGetRecIdFromKeyOperationCompleted(object arg) {
            if ((this.GetRecIdFromKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRecIdFromKeyCompleted(this, new GetRecIdFromKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/ws_nav_vendor:Create", RequestNamespace="urn:microsoft-dynamics-schemas/page/ws_nav_vendor", ResponseElementName="Create_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/ws_nav_vendor", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Create(ref WS_NAV_Vendor WS_NAV_Vendor) {
            object[] results = this.Invoke("Create", new object[] {
                        WS_NAV_Vendor});
            WS_NAV_Vendor = ((WS_NAV_Vendor)(results[0]));
        }
        
        /// <remarks/>
        public void CreateAsync(WS_NAV_Vendor WS_NAV_Vendor) {
            this.CreateAsync(WS_NAV_Vendor, null);
        }
        
        /// <remarks/>
        public void CreateAsync(WS_NAV_Vendor WS_NAV_Vendor, object userState) {
            if ((this.CreateOperationCompleted == null)) {
                this.CreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOperationCompleted);
            }
            this.InvokeAsync("Create", new object[] {
                        WS_NAV_Vendor}, this.CreateOperationCompleted, userState);
        }
        
        private void OnCreateOperationCompleted(object arg) {
            if ((this.CreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCompleted(this, new CreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/ws_nav_vendor:CreateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/ws_nav_vendor", ResponseElementName="CreateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/ws_nav_vendor", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref WS_NAV_Vendor[] WS_NAV_Vendor_List) {
            object[] results = this.Invoke("CreateMultiple", new object[] {
                        WS_NAV_Vendor_List});
            WS_NAV_Vendor_List = ((WS_NAV_Vendor[])(results[0]));
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(WS_NAV_Vendor[] WS_NAV_Vendor_List) {
            this.CreateMultipleAsync(WS_NAV_Vendor_List, null);
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(WS_NAV_Vendor[] WS_NAV_Vendor_List, object userState) {
            if ((this.CreateMultipleOperationCompleted == null)) {
                this.CreateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateMultipleOperationCompleted);
            }
            this.InvokeAsync("CreateMultiple", new object[] {
                        WS_NAV_Vendor_List}, this.CreateMultipleOperationCompleted, userState);
        }
        
        private void OnCreateMultipleOperationCompleted(object arg) {
            if ((this.CreateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateMultipleCompleted(this, new CreateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/ws_nav_vendor:Update", RequestNamespace="urn:microsoft-dynamics-schemas/page/ws_nav_vendor", ResponseElementName="Update_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/ws_nav_vendor", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Update(ref WS_NAV_Vendor WS_NAV_Vendor) {
            object[] results = this.Invoke("Update", new object[] {
                        WS_NAV_Vendor});
            WS_NAV_Vendor = ((WS_NAV_Vendor)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAsync(WS_NAV_Vendor WS_NAV_Vendor) {
            this.UpdateAsync(WS_NAV_Vendor, null);
        }
        
        /// <remarks/>
        public void UpdateAsync(WS_NAV_Vendor WS_NAV_Vendor, object userState) {
            if ((this.UpdateOperationCompleted == null)) {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                        WS_NAV_Vendor}, this.UpdateOperationCompleted, userState);
        }
        
        private void OnUpdateOperationCompleted(object arg) {
            if ((this.UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/ws_nav_vendor:UpdateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/ws_nav_vendor", ResponseElementName="UpdateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/ws_nav_vendor", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref WS_NAV_Vendor[] WS_NAV_Vendor_List) {
            object[] results = this.Invoke("UpdateMultiple", new object[] {
                        WS_NAV_Vendor_List});
            WS_NAV_Vendor_List = ((WS_NAV_Vendor[])(results[0]));
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(WS_NAV_Vendor[] WS_NAV_Vendor_List) {
            this.UpdateMultipleAsync(WS_NAV_Vendor_List, null);
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(WS_NAV_Vendor[] WS_NAV_Vendor_List, object userState) {
            if ((this.UpdateMultipleOperationCompleted == null)) {
                this.UpdateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMultipleOperationCompleted);
            }
            this.InvokeAsync("UpdateMultiple", new object[] {
                        WS_NAV_Vendor_List}, this.UpdateMultipleOperationCompleted, userState);
        }
        
        private void OnUpdateMultipleOperationCompleted(object arg) {
            if ((this.UpdateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMultipleCompleted(this, new UpdateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/ws_nav_vendor:Delete", RequestNamespace="urn:microsoft-dynamics-schemas/page/ws_nav_vendor", ResponseElementName="Delete_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/ws_nav_vendor", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_Result")]
        public bool Delete(string Key) {
            object[] results = this.Invoke("Delete", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteAsync(string Key) {
            this.DeleteAsync(Key, null);
        }
        
        /// <remarks/>
        public void DeleteAsync(string Key, object userState) {
            if ((this.DeleteOperationCompleted == null)) {
                this.DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteOperationCompleted);
            }
            this.InvokeAsync("Delete", new object[] {
                        Key}, this.DeleteOperationCompleted, userState);
        }
        
        private void OnDeleteOperationCompleted(object arg) {
            if ((this.DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCompleted(this, new DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/ws_nav_vendor")]
    public partial class WS_NAV_Vendor {
        
        private string keyField;
        
        private string noField;
        
        private string nameField;
        
        private string addressField;
        
        private string address_2Field;
        
        private string post_CodeField;
        
        private string cityField;
        
        private string country_Region_CodeField;
        
        private string state_CodeField;
        
        private bool transporterField;
        
        private bool transporterFieldSpecified;
        
        private string phone_NoField;
        
        private string primary_Contact_NoField;
        
        private string contactField;
        
        private string search_NameField;
        
        private decimal balance_LCYField;
        
        private bool balance_LCYFieldSpecified;
        
        private decimal balanceField;
        
        private bool balanceFieldSpecified;
        
        private decimal net_Change_LCYField;
        
        private bool net_Change_LCYFieldSpecified;
        
        private decimal net_ChangeField;
        
        private bool net_ChangeFieldSpecified;
        
        private string main_PaymentField;
        
        private string sub_PaymentField;
        
        private string purchaser_CodeField;
        
        private string responsibility_CenterField;
        
        private Blocked blockedField;
        
        private bool blockedFieldSpecified;
        
        private bool aging_ReportField;
        
        private bool aging_ReportFieldSpecified;
        
        private string created_ByField;
        
        private System.DateTime created_DateField;
        
        private bool created_DateFieldSpecified;
        
        private string modify_ByField;
        
        private System.DateTime last_Date_ModifiedField;
        
        private bool last_Date_ModifiedFieldSpecified;
        
        private string fax_NoField;
        
        private string e_MailField;
        
        private string home_PageField;
        
        private string iC_Partner_CodeField;
        
        private string sTD_CodeField;
        
        private string mobile_NoField;
        
        private string pay_to_Vendor_NoField;
        
        private bool tax_LiableField;
        
        private bool tax_LiableFieldSpecified;
        
        private string structureField;
        
        private bool sSIField;
        
        private bool sSIFieldSpecified;
        
        private System.DateTime sSI_Validity_DateField;
        
        private bool sSI_Validity_DateFieldSpecified;
        
        private string gen_Bus_Posting_GroupField;
        
        private string vAT_Bus_Posting_GroupField;
        
        private string excise_Bus_Posting_GroupField;
        
        private string vendor_Posting_GroupField;
        
        private string invoice_Disc_CodeField;
        
        private bool prices_Including_VATField;
        
        private bool prices_Including_VATFieldSpecified;
        
        private decimal prepayment_PercentField;
        
        private bool prepayment_PercentFieldSpecified;
        
        private Application_Method application_MethodField;
        
        private bool application_MethodFieldSpecified;
        
        private Partner_Type partner_TypeField;
        
        private bool partner_TypeFieldSpecified;
        
        private string payment_Terms_CodeField;
        
        private string currency_CodeField;
        
        private string payment_Method_CodeField;
        
        private int priorityField;
        
        private bool priorityFieldSpecified;
        
        private string iFSC_CodeField;
        
        private Account_Type account_TypeField;
        
        private bool account_TypeFieldSpecified;
        
        private string bank_NameField;
        
        private string bank_BranchField;
        
        private string cash_Flow_Payment_Terms_CodeField;
        
        private string our_Account_NoField;
        
        private string mobile_No_RTGSField;
        
        private string email_RTGSField;
        
        private bool block_Payment_ToleranceField;
        
        private bool block_Payment_ToleranceFieldSpecified;
        
        private string creditor_NoField;
        
        private string preferred_Bank_AccountField;
        
        private string location_CodeField;
        
        private string shipment_Method_CodeField;
        
        private string lead_Time_CalculationField;
        
        private string base_Calendar_CodeField;
        
        private string customized_CalendarField;
        
        private string language_CodeField;
        
        private string vAT_Registration_NoField;
        
        private string l_S_T_NoField;
        
        private string c_S_T_NoField;
        
        private string e_C_C_NoField;
        
        private string rangeField;
        
        private string collectorateField;
        
        private Vendor_Type vendor_TypeField;
        
        private bool vendor_TypeFieldSpecified;
        
        private string t_I_N_NoField;
        
        private bool compositionField;
        
        private bool compositionFieldSpecified;
        
        private string p_A_N_NoField;
        
        private P_A_N_Status p_A_N_StatusField;
        
        private bool p_A_N_StatusFieldSpecified;
        
        private string p_A_N_Reference_NoField;
        
        private string service_Entity_TypeField;
        
        private string service_Tax_Registration_NoField;
        
        private bool subcontractorField;
        
        private bool subcontractorFieldSpecified;
        
        private string vendor_LocationField;
        
        private string commissioners_Permission_NoField;
        
        private string rework_LocationField;
        
        private string mSME_NoField;
        
        private string sIA_NoField;
        
        private string pF_NoField;
        
        private string eSI_NoField;
        
        private string authorised_ByField;
        
        private string reference_Code_InternalField;
        
        private string reference_Code_ExternalField;
        
        private string ex_Reference_Mobile_NoField;
        
        private string pDPNameField;
        
        private string pDPPhoneNoField;
        
        private string pDPMobileNoField;
        
        private string pDPEmailIDField;
        
        private string sales_Dept_NameField;
        
        private string sales_Dept_PhoneNoField;
        
        private string sales_Dept_MobileNoField;
        
        private string sales_Dept_EmailIDField;
        
        private string account_Dept_NameField;
        
        private string account_Dept_PhoneNoField;
        
        private string account_Dept_MobileNoField;
        
        private string account_Dept_EmailIDField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string Address_2 {
            get {
                return this.address_2Field;
            }
            set {
                this.address_2Field = value;
            }
        }
        
        /// <remarks/>
        public string Post_Code {
            get {
                return this.post_CodeField;
            }
            set {
                this.post_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string Country_Region_Code {
            get {
                return this.country_Region_CodeField;
            }
            set {
                this.country_Region_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string State_Code {
            get {
                return this.state_CodeField;
            }
            set {
                this.state_CodeField = value;
            }
        }
        
        /// <remarks/>
        public bool Transporter {
            get {
                return this.transporterField;
            }
            set {
                this.transporterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransporterSpecified {
            get {
                return this.transporterFieldSpecified;
            }
            set {
                this.transporterFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Phone_No {
            get {
                return this.phone_NoField;
            }
            set {
                this.phone_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Primary_Contact_No {
            get {
                return this.primary_Contact_NoField;
            }
            set {
                this.primary_Contact_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        public string Search_Name {
            get {
                return this.search_NameField;
            }
            set {
                this.search_NameField = value;
            }
        }
        
        /// <remarks/>
        public decimal Balance_LCY {
            get {
                return this.balance_LCYField;
            }
            set {
                this.balance_LCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Balance_LCYSpecified {
            get {
                return this.balance_LCYFieldSpecified;
            }
            set {
                this.balance_LCYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BalanceSpecified {
            get {
                return this.balanceFieldSpecified;
            }
            set {
                this.balanceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Net_Change_LCY {
            get {
                return this.net_Change_LCYField;
            }
            set {
                this.net_Change_LCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Net_Change_LCYSpecified {
            get {
                return this.net_Change_LCYFieldSpecified;
            }
            set {
                this.net_Change_LCYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Net_Change {
            get {
                return this.net_ChangeField;
            }
            set {
                this.net_ChangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Net_ChangeSpecified {
            get {
                return this.net_ChangeFieldSpecified;
            }
            set {
                this.net_ChangeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Main_Payment {
            get {
                return this.main_PaymentField;
            }
            set {
                this.main_PaymentField = value;
            }
        }
        
        /// <remarks/>
        public string Sub_Payment {
            get {
                return this.sub_PaymentField;
            }
            set {
                this.sub_PaymentField = value;
            }
        }
        
        /// <remarks/>
        public string Purchaser_Code {
            get {
                return this.purchaser_CodeField;
            }
            set {
                this.purchaser_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Responsibility_Center {
            get {
                return this.responsibility_CenterField;
            }
            set {
                this.responsibility_CenterField = value;
            }
        }
        
        /// <remarks/>
        public Blocked Blocked {
            get {
                return this.blockedField;
            }
            set {
                this.blockedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BlockedSpecified {
            get {
                return this.blockedFieldSpecified;
            }
            set {
                this.blockedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Aging_Report {
            get {
                return this.aging_ReportField;
            }
            set {
                this.aging_ReportField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Aging_ReportSpecified {
            get {
                return this.aging_ReportFieldSpecified;
            }
            set {
                this.aging_ReportFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Created_By {
            get {
                return this.created_ByField;
            }
            set {
                this.created_ByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Created_Date {
            get {
                return this.created_DateField;
            }
            set {
                this.created_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Created_DateSpecified {
            get {
                return this.created_DateFieldSpecified;
            }
            set {
                this.created_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Modify_By {
            get {
                return this.modify_ByField;
            }
            set {
                this.modify_ByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Last_Date_Modified {
            get {
                return this.last_Date_ModifiedField;
            }
            set {
                this.last_Date_ModifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Last_Date_ModifiedSpecified {
            get {
                return this.last_Date_ModifiedFieldSpecified;
            }
            set {
                this.last_Date_ModifiedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Fax_No {
            get {
                return this.fax_NoField;
            }
            set {
                this.fax_NoField = value;
            }
        }
        
        /// <remarks/>
        public string E_Mail {
            get {
                return this.e_MailField;
            }
            set {
                this.e_MailField = value;
            }
        }
        
        /// <remarks/>
        public string Home_Page {
            get {
                return this.home_PageField;
            }
            set {
                this.home_PageField = value;
            }
        }
        
        /// <remarks/>
        public string IC_Partner_Code {
            get {
                return this.iC_Partner_CodeField;
            }
            set {
                this.iC_Partner_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string STD_Code {
            get {
                return this.sTD_CodeField;
            }
            set {
                this.sTD_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Mobile_No {
            get {
                return this.mobile_NoField;
            }
            set {
                this.mobile_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Pay_to_Vendor_No {
            get {
                return this.pay_to_Vendor_NoField;
            }
            set {
                this.pay_to_Vendor_NoField = value;
            }
        }
        
        /// <remarks/>
        public bool Tax_Liable {
            get {
                return this.tax_LiableField;
            }
            set {
                this.tax_LiableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Tax_LiableSpecified {
            get {
                return this.tax_LiableFieldSpecified;
            }
            set {
                this.tax_LiableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Structure {
            get {
                return this.structureField;
            }
            set {
                this.structureField = value;
            }
        }
        
        /// <remarks/>
        public bool SSI {
            get {
                return this.sSIField;
            }
            set {
                this.sSIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SSISpecified {
            get {
                return this.sSIFieldSpecified;
            }
            set {
                this.sSIFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime SSI_Validity_Date {
            get {
                return this.sSI_Validity_DateField;
            }
            set {
                this.sSI_Validity_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SSI_Validity_DateSpecified {
            get {
                return this.sSI_Validity_DateFieldSpecified;
            }
            set {
                this.sSI_Validity_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Gen_Bus_Posting_Group {
            get {
                return this.gen_Bus_Posting_GroupField;
            }
            set {
                this.gen_Bus_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        public string VAT_Bus_Posting_Group {
            get {
                return this.vAT_Bus_Posting_GroupField;
            }
            set {
                this.vAT_Bus_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        public string Excise_Bus_Posting_Group {
            get {
                return this.excise_Bus_Posting_GroupField;
            }
            set {
                this.excise_Bus_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        public string Vendor_Posting_Group {
            get {
                return this.vendor_Posting_GroupField;
            }
            set {
                this.vendor_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_Disc_Code {
            get {
                return this.invoice_Disc_CodeField;
            }
            set {
                this.invoice_Disc_CodeField = value;
            }
        }
        
        /// <remarks/>
        public bool Prices_Including_VAT {
            get {
                return this.prices_Including_VATField;
            }
            set {
                this.prices_Including_VATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Prices_Including_VATSpecified {
            get {
                return this.prices_Including_VATFieldSpecified;
            }
            set {
                this.prices_Including_VATFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Prepayment_Percent {
            get {
                return this.prepayment_PercentField;
            }
            set {
                this.prepayment_PercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Prepayment_PercentSpecified {
            get {
                return this.prepayment_PercentFieldSpecified;
            }
            set {
                this.prepayment_PercentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Application_Method Application_Method {
            get {
                return this.application_MethodField;
            }
            set {
                this.application_MethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Application_MethodSpecified {
            get {
                return this.application_MethodFieldSpecified;
            }
            set {
                this.application_MethodFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Partner_Type Partner_Type {
            get {
                return this.partner_TypeField;
            }
            set {
                this.partner_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Partner_TypeSpecified {
            get {
                return this.partner_TypeFieldSpecified;
            }
            set {
                this.partner_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Payment_Terms_Code {
            get {
                return this.payment_Terms_CodeField;
            }
            set {
                this.payment_Terms_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Currency_Code {
            get {
                return this.currency_CodeField;
            }
            set {
                this.currency_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Payment_Method_Code {
            get {
                return this.payment_Method_CodeField;
            }
            set {
                this.payment_Method_CodeField = value;
            }
        }
        
        /// <remarks/>
        public int Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrioritySpecified {
            get {
                return this.priorityFieldSpecified;
            }
            set {
                this.priorityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string IFSC_Code {
            get {
                return this.iFSC_CodeField;
            }
            set {
                this.iFSC_CodeField = value;
            }
        }
        
        /// <remarks/>
        public Account_Type Account_Type {
            get {
                return this.account_TypeField;
            }
            set {
                this.account_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Account_TypeSpecified {
            get {
                return this.account_TypeFieldSpecified;
            }
            set {
                this.account_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Bank_Name {
            get {
                return this.bank_NameField;
            }
            set {
                this.bank_NameField = value;
            }
        }
        
        /// <remarks/>
        public string Bank_Branch {
            get {
                return this.bank_BranchField;
            }
            set {
                this.bank_BranchField = value;
            }
        }
        
        /// <remarks/>
        public string Cash_Flow_Payment_Terms_Code {
            get {
                return this.cash_Flow_Payment_Terms_CodeField;
            }
            set {
                this.cash_Flow_Payment_Terms_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Our_Account_No {
            get {
                return this.our_Account_NoField;
            }
            set {
                this.our_Account_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Mobile_No_RTGS {
            get {
                return this.mobile_No_RTGSField;
            }
            set {
                this.mobile_No_RTGSField = value;
            }
        }
        
        /// <remarks/>
        public string Email_RTGS {
            get {
                return this.email_RTGSField;
            }
            set {
                this.email_RTGSField = value;
            }
        }
        
        /// <remarks/>
        public bool Block_Payment_Tolerance {
            get {
                return this.block_Payment_ToleranceField;
            }
            set {
                this.block_Payment_ToleranceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Block_Payment_ToleranceSpecified {
            get {
                return this.block_Payment_ToleranceFieldSpecified;
            }
            set {
                this.block_Payment_ToleranceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Creditor_No {
            get {
                return this.creditor_NoField;
            }
            set {
                this.creditor_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Preferred_Bank_Account {
            get {
                return this.preferred_Bank_AccountField;
            }
            set {
                this.preferred_Bank_AccountField = value;
            }
        }
        
        /// <remarks/>
        public string Location_Code {
            get {
                return this.location_CodeField;
            }
            set {
                this.location_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Shipment_Method_Code {
            get {
                return this.shipment_Method_CodeField;
            }
            set {
                this.shipment_Method_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Lead_Time_Calculation {
            get {
                return this.lead_Time_CalculationField;
            }
            set {
                this.lead_Time_CalculationField = value;
            }
        }
        
        /// <remarks/>
        public string Base_Calendar_Code {
            get {
                return this.base_Calendar_CodeField;
            }
            set {
                this.base_Calendar_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Customized_Calendar {
            get {
                return this.customized_CalendarField;
            }
            set {
                this.customized_CalendarField = value;
            }
        }
        
        /// <remarks/>
        public string Language_Code {
            get {
                return this.language_CodeField;
            }
            set {
                this.language_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string VAT_Registration_No {
            get {
                return this.vAT_Registration_NoField;
            }
            set {
                this.vAT_Registration_NoField = value;
            }
        }
        
        /// <remarks/>
        public string L_S_T_No {
            get {
                return this.l_S_T_NoField;
            }
            set {
                this.l_S_T_NoField = value;
            }
        }
        
        /// <remarks/>
        public string C_S_T_No {
            get {
                return this.c_S_T_NoField;
            }
            set {
                this.c_S_T_NoField = value;
            }
        }
        
        /// <remarks/>
        public string E_C_C_No {
            get {
                return this.e_C_C_NoField;
            }
            set {
                this.e_C_C_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Range {
            get {
                return this.rangeField;
            }
            set {
                this.rangeField = value;
            }
        }
        
        /// <remarks/>
        public string Collectorate {
            get {
                return this.collectorateField;
            }
            set {
                this.collectorateField = value;
            }
        }
        
        /// <remarks/>
        public Vendor_Type Vendor_Type {
            get {
                return this.vendor_TypeField;
            }
            set {
                this.vendor_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Vendor_TypeSpecified {
            get {
                return this.vendor_TypeFieldSpecified;
            }
            set {
                this.vendor_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string T_I_N_No {
            get {
                return this.t_I_N_NoField;
            }
            set {
                this.t_I_N_NoField = value;
            }
        }
        
        /// <remarks/>
        public bool Composition {
            get {
                return this.compositionField;
            }
            set {
                this.compositionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CompositionSpecified {
            get {
                return this.compositionFieldSpecified;
            }
            set {
                this.compositionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string P_A_N_No {
            get {
                return this.p_A_N_NoField;
            }
            set {
                this.p_A_N_NoField = value;
            }
        }
        
        /// <remarks/>
        public P_A_N_Status P_A_N_Status {
            get {
                return this.p_A_N_StatusField;
            }
            set {
                this.p_A_N_StatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_A_N_StatusSpecified {
            get {
                return this.p_A_N_StatusFieldSpecified;
            }
            set {
                this.p_A_N_StatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string P_A_N_Reference_No {
            get {
                return this.p_A_N_Reference_NoField;
            }
            set {
                this.p_A_N_Reference_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Service_Entity_Type {
            get {
                return this.service_Entity_TypeField;
            }
            set {
                this.service_Entity_TypeField = value;
            }
        }
        
        /// <remarks/>
        public string Service_Tax_Registration_No {
            get {
                return this.service_Tax_Registration_NoField;
            }
            set {
                this.service_Tax_Registration_NoField = value;
            }
        }
        
        /// <remarks/>
        public bool Subcontractor {
            get {
                return this.subcontractorField;
            }
            set {
                this.subcontractorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SubcontractorSpecified {
            get {
                return this.subcontractorFieldSpecified;
            }
            set {
                this.subcontractorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Vendor_Location {
            get {
                return this.vendor_LocationField;
            }
            set {
                this.vendor_LocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Commissioner\'s_Permission_No")]
        public string Commissioners_Permission_No {
            get {
                return this.commissioners_Permission_NoField;
            }
            set {
                this.commissioners_Permission_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Rework_Location {
            get {
                return this.rework_LocationField;
            }
            set {
                this.rework_LocationField = value;
            }
        }
        
        /// <remarks/>
        public string MSME_No {
            get {
                return this.mSME_NoField;
            }
            set {
                this.mSME_NoField = value;
            }
        }
        
        /// <remarks/>
        public string SIA_No {
            get {
                return this.sIA_NoField;
            }
            set {
                this.sIA_NoField = value;
            }
        }
        
        /// <remarks/>
        public string PF_No {
            get {
                return this.pF_NoField;
            }
            set {
                this.pF_NoField = value;
            }
        }
        
        /// <remarks/>
        public string ESI_No {
            get {
                return this.eSI_NoField;
            }
            set {
                this.eSI_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Authorised_By {
            get {
                return this.authorised_ByField;
            }
            set {
                this.authorised_ByField = value;
            }
        }
        
        /// <remarks/>
        public string Reference_Code_Internal {
            get {
                return this.reference_Code_InternalField;
            }
            set {
                this.reference_Code_InternalField = value;
            }
        }
        
        /// <remarks/>
        public string Reference_Code_External {
            get {
                return this.reference_Code_ExternalField;
            }
            set {
                this.reference_Code_ExternalField = value;
            }
        }
        
        /// <remarks/>
        public string Ex_Reference_Mobile_No {
            get {
                return this.ex_Reference_Mobile_NoField;
            }
            set {
                this.ex_Reference_Mobile_NoField = value;
            }
        }
        
        /// <remarks/>
        public string PDPName {
            get {
                return this.pDPNameField;
            }
            set {
                this.pDPNameField = value;
            }
        }
        
        /// <remarks/>
        public string PDPPhoneNo {
            get {
                return this.pDPPhoneNoField;
            }
            set {
                this.pDPPhoneNoField = value;
            }
        }
        
        /// <remarks/>
        public string PDPMobileNo {
            get {
                return this.pDPMobileNoField;
            }
            set {
                this.pDPMobileNoField = value;
            }
        }
        
        /// <remarks/>
        public string PDPEmailID {
            get {
                return this.pDPEmailIDField;
            }
            set {
                this.pDPEmailIDField = value;
            }
        }
        
        /// <remarks/>
        public string Sales_Dept_Name {
            get {
                return this.sales_Dept_NameField;
            }
            set {
                this.sales_Dept_NameField = value;
            }
        }
        
        /// <remarks/>
        public string Sales_Dept_PhoneNo {
            get {
                return this.sales_Dept_PhoneNoField;
            }
            set {
                this.sales_Dept_PhoneNoField = value;
            }
        }
        
        /// <remarks/>
        public string Sales_Dept_MobileNo {
            get {
                return this.sales_Dept_MobileNoField;
            }
            set {
                this.sales_Dept_MobileNoField = value;
            }
        }
        
        /// <remarks/>
        public string Sales_Dept_EmailID {
            get {
                return this.sales_Dept_EmailIDField;
            }
            set {
                this.sales_Dept_EmailIDField = value;
            }
        }
        
        /// <remarks/>
        public string Account_Dept_Name {
            get {
                return this.account_Dept_NameField;
            }
            set {
                this.account_Dept_NameField = value;
            }
        }
        
        /// <remarks/>
        public string Account_Dept_PhoneNo {
            get {
                return this.account_Dept_PhoneNoField;
            }
            set {
                this.account_Dept_PhoneNoField = value;
            }
        }
        
        /// <remarks/>
        public string Account_Dept_MobileNo {
            get {
                return this.account_Dept_MobileNoField;
            }
            set {
                this.account_Dept_MobileNoField = value;
            }
        }
        
        /// <remarks/>
        public string Account_Dept_EmailID {
            get {
                return this.account_Dept_EmailIDField;
            }
            set {
                this.account_Dept_EmailIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/ws_nav_vendor")]
    public enum Blocked {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Payment,
        
        /// <remarks/>
        All,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/ws_nav_vendor")]
    public enum Application_Method {
        
        /// <remarks/>
        Manual,
        
        /// <remarks/>
        Apply_to_Oldest,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/ws_nav_vendor")]
    public enum Partner_Type {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Company,
        
        /// <remarks/>
        Person,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/ws_nav_vendor")]
    public enum Account_Type {
        
        /// <remarks/>
        Saving,
        
        /// <remarks/>
        Current,
        
        /// <remarks/>
        CC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/ws_nav_vendor")]
    public enum Vendor_Type {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Manufacturer,
        
        /// <remarks/>
        First_Stage_Dealer,
        
        /// <remarks/>
        Second_Stage_Dealer,
        
        /// <remarks/>
        Importer,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/ws_nav_vendor")]
    public enum P_A_N_Status {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        PANAPPLIED,
        
        /// <remarks/>
        PANINVALID,
        
        /// <remarks/>
        PANNOTAVBL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/ws_nav_vendor")]
    public partial class WS_NAV_Vendor_Filter {
        
        private WS_NAV_Vendor_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        public WS_NAV_Vendor_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/ws_nav_vendor")]
    public enum WS_NAV_Vendor_Fields {
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        Name,
        
        /// <remarks/>
        Address,
        
        /// <remarks/>
        Address_2,
        
        /// <remarks/>
        Post_Code,
        
        /// <remarks/>
        City,
        
        /// <remarks/>
        Country_Region_Code,
        
        /// <remarks/>
        State_Code,
        
        /// <remarks/>
        Transporter,
        
        /// <remarks/>
        Phone_No,
        
        /// <remarks/>
        Primary_Contact_No,
        
        /// <remarks/>
        Contact,
        
        /// <remarks/>
        Search_Name,
        
        /// <remarks/>
        Balance_LCY,
        
        /// <remarks/>
        Balance,
        
        /// <remarks/>
        Net_Change_LCY,
        
        /// <remarks/>
        Net_Change,
        
        /// <remarks/>
        Main_Payment,
        
        /// <remarks/>
        Sub_Payment,
        
        /// <remarks/>
        Purchaser_Code,
        
        /// <remarks/>
        Responsibility_Center,
        
        /// <remarks/>
        Blocked,
        
        /// <remarks/>
        Aging_Report,
        
        /// <remarks/>
        Created_By,
        
        /// <remarks/>
        Created_Date,
        
        /// <remarks/>
        Modify_By,
        
        /// <remarks/>
        Last_Date_Modified,
        
        /// <remarks/>
        Fax_No,
        
        /// <remarks/>
        E_Mail,
        
        /// <remarks/>
        Home_Page,
        
        /// <remarks/>
        IC_Partner_Code,
        
        /// <remarks/>
        STD_Code,
        
        /// <remarks/>
        Mobile_No,
        
        /// <remarks/>
        Pay_to_Vendor_No,
        
        /// <remarks/>
        Tax_Liable,
        
        /// <remarks/>
        Structure,
        
        /// <remarks/>
        SSI,
        
        /// <remarks/>
        SSI_Validity_Date,
        
        /// <remarks/>
        Gen_Bus_Posting_Group,
        
        /// <remarks/>
        VAT_Bus_Posting_Group,
        
        /// <remarks/>
        Excise_Bus_Posting_Group,
        
        /// <remarks/>
        Vendor_Posting_Group,
        
        /// <remarks/>
        Invoice_Disc_Code,
        
        /// <remarks/>
        Prices_Including_VAT,
        
        /// <remarks/>
        Prepayment_Percent,
        
        /// <remarks/>
        Application_Method,
        
        /// <remarks/>
        Partner_Type,
        
        /// <remarks/>
        Payment_Terms_Code,
        
        /// <remarks/>
        Currency_Code,
        
        /// <remarks/>
        Payment_Method_Code,
        
        /// <remarks/>
        Priority,
        
        /// <remarks/>
        IFSC_Code,
        
        /// <remarks/>
        Account_Type,
        
        /// <remarks/>
        Bank_Name,
        
        /// <remarks/>
        Bank_Branch,
        
        /// <remarks/>
        Cash_Flow_Payment_Terms_Code,
        
        /// <remarks/>
        Our_Account_No,
        
        /// <remarks/>
        Mobile_No_RTGS,
        
        /// <remarks/>
        Email_RTGS,
        
        /// <remarks/>
        Block_Payment_Tolerance,
        
        /// <remarks/>
        Creditor_No,
        
        /// <remarks/>
        Preferred_Bank_Account,
        
        /// <remarks/>
        Location_Code,
        
        /// <remarks/>
        Shipment_Method_Code,
        
        /// <remarks/>
        Lead_Time_Calculation,
        
        /// <remarks/>
        Base_Calendar_Code,
        
        /// <remarks/>
        Customized_Calendar,
        
        /// <remarks/>
        Language_Code,
        
        /// <remarks/>
        VAT_Registration_No,
        
        /// <remarks/>
        L_S_T_No,
        
        /// <remarks/>
        C_S_T_No,
        
        /// <remarks/>
        E_C_C_No,
        
        /// <remarks/>
        Range,
        
        /// <remarks/>
        Collectorate,
        
        /// <remarks/>
        Vendor_Type,
        
        /// <remarks/>
        T_I_N_No,
        
        /// <remarks/>
        Composition,
        
        /// <remarks/>
        P_A_N_No,
        
        /// <remarks/>
        P_A_N_Status,
        
        /// <remarks/>
        P_A_N_Reference_No,
        
        /// <remarks/>
        Service_Entity_Type,
        
        /// <remarks/>
        Service_Tax_Registration_No,
        
        /// <remarks/>
        Subcontractor,
        
        /// <remarks/>
        Vendor_Location,
        
        /// <remarks/>
        Commissioner_x0027_s_Permission_No,
        
        /// <remarks/>
        Rework_Location,
        
        /// <remarks/>
        MSME_No,
        
        /// <remarks/>
        SIA_No,
        
        /// <remarks/>
        PF_No,
        
        /// <remarks/>
        ESI_No,
        
        /// <remarks/>
        Authorised_By,
        
        /// <remarks/>
        Reference_Code_Internal,
        
        /// <remarks/>
        Reference_Code_External,
        
        /// <remarks/>
        Ex_Reference_Mobile_No,
        
        /// <remarks/>
        PDPName,
        
        /// <remarks/>
        PDPPhoneNo,
        
        /// <remarks/>
        PDPMobileNo,
        
        /// <remarks/>
        PDPEmailID,
        
        /// <remarks/>
        Sales_Dept_Name,
        
        /// <remarks/>
        Sales_Dept_PhoneNo,
        
        /// <remarks/>
        Sales_Dept_MobileNo,
        
        /// <remarks/>
        Sales_Dept_EmailID,
        
        /// <remarks/>
        Account_Dept_Name,
        
        /// <remarks/>
        Account_Dept_PhoneNo,
        
        /// <remarks/>
        Account_Dept_MobileNo,
        
        /// <remarks/>
        Account_Dept_EmailID,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ReadCompletedEventHandler(object sender, ReadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WS_NAV_Vendor Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WS_NAV_Vendor)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ReadByRecIdCompletedEventHandler(object sender, ReadByRecIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadByRecIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadByRecIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WS_NAV_Vendor Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WS_NAV_Vendor)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ReadMultipleCompletedEventHandler(object sender, ReadMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WS_NAV_Vendor[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WS_NAV_Vendor[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void IsUpdatedCompletedEventHandler(object sender, IsUpdatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsUpdatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsUpdatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetRecIdFromKeyCompletedEventHandler(object sender, GetRecIdFromKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRecIdFromKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRecIdFromKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void CreateCompletedEventHandler(object sender, CreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WS_NAV_Vendor WS_NAV_Vendor {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WS_NAV_Vendor)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void CreateMultipleCompletedEventHandler(object sender, CreateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WS_NAV_Vendor[] WS_NAV_Vendor_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WS_NAV_Vendor[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void UpdateCompletedEventHandler(object sender, UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WS_NAV_Vendor WS_NAV_Vendor {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WS_NAV_Vendor)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void UpdateMultipleCompletedEventHandler(object sender, UpdateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WS_NAV_Vendor[] WS_NAV_Vendor_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WS_NAV_Vendor[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void DeleteCompletedEventHandler(object sender, DeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591