//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCILVendorPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Busi_Cust_Ref
    {
        public int ID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public string Customer_Name { get; set; }
        public string Location { get; set; }
        public string Contact_Person { get; set; }
        public Nullable<decimal> Contact_Number { get; set; }
    
        public virtual VendorRegistration VendorRegistration { get; set; }
    }
}
