//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCILVendorPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Busi_Annul_Turnover
    {
        public int ID { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<int> YearFirst { get; set; }
        public Nullable<int> YearSecond { get; set; }
        public Nullable<int> YearThird { get; set; }
        public Nullable<decimal> YearFirstTurnOver { get; set; }
        public Nullable<decimal> YearSecondTurnOver { get; set; }
        public Nullable<decimal> YearThirdTurnOver { get; set; }
    
        public virtual VendorRegistration VendorRegistration { get; set; }
        public virtual VendorRegistration VendorRegistration1 { get; set; }
    }
}
