//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCILVendorPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardMenu
    {
        public DashboardMenu()
        {
            this.VendorAccessLogs = new HashSet<VendorAccessLog>();
        }
    
        public int ID { get; set; }
        public string DashboardLabel { get; set; }
        public string DashboardLink { get; set; }
        public Nullable<bool> Activate { get; set; }
        public Nullable<int> TypeOfUser { get; set; }
        public Nullable<decimal> Counter { get; set; }
        public string Class { get; set; }
    
        public virtual ICollection<VendorAccessLog> VendorAccessLogs { get; set; }
    }
}
