//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCILVendorPortal
{
    using System;
    
    public partial class NewOpenVendorList_Result1
    {
        public int ID { get; set; }
        public string VendorCode { get; set; }
        public string TypeOfBusiness { get; set; }
        public string Title { get; set; }
        public string VendorName_HO { get; set; }
        public Nullable<System.DateTime> Last_date_modified { get; set; }
        public Nullable<bool> FeedBack { get; set; }
    }
}
