//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCILVendorPortal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class EDMXConnectionString : DbContext
    {
        public EDMXConnectionString()
            : base("name=EDMXConnectionString")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Busi_Annul_Turnover> Busi_Annul_Turnover { get; set; }
        public DbSet<Busi_Cust_Ref> Busi_Cust_Ref { get; set; }
        public DbSet<DashboardMenu> DashboardMenus { get; set; }
        public DbSet<LogHistory> LogHistories { get; set; }
        public DbSet<VendorAccessLog> VendorAccessLogs { get; set; }
        public DbSet<VendorLogin> VendorLogins { get; set; }
        public DbSet<VendorRegistration> VendorRegistrations { get; set; }    
        
    }
}
