//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCILVendorPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorAccessLog
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int MenuAccessID { get; set; }
        public bool Active { get; set; }
    
        public virtual DashboardMenu DashboardMenu { get; set; }
        public virtual VendorLogin VendorLogin { get; set; }
    }
}
