#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendorLib
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="VendorPortal")]
	public partial class VendorLinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBusi_Annul_Turnover(Busi_Annul_Turnover instance);
    partial void UpdateBusi_Annul_Turnover(Busi_Annul_Turnover instance);
    partial void DeleteBusi_Annul_Turnover(Busi_Annul_Turnover instance);
    partial void InsertBusi_Cust_Ref(Busi_Cust_Ref instance);
    partial void UpdateBusi_Cust_Ref(Busi_Cust_Ref instance);
    partial void DeleteBusi_Cust_Ref(Busi_Cust_Ref instance);
    partial void InsertTable(Table instance);
    partial void UpdateTable(Table instance);
    partial void DeleteTable(Table instance);
    partial void InsertVendorLogin(VendorLogin instance);
    partial void UpdateVendorLogin(VendorLogin instance);
    partial void DeleteVendorLogin(VendorLogin instance);
    partial void InsertVendorRegistration(VendorRegistration instance);
    partial void UpdateVendorRegistration(VendorRegistration instance);
    partial void DeleteVendorRegistration(VendorRegistration instance);
    #endregion
		
		public VendorLinqDataContext() : 
				base(global::VendorLib.Properties.Settings.Default.VendorPortalConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public VendorLinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VendorLinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VendorLinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VendorLinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Busi_Annul_Turnover> Busi_Annul_Turnovers
		{
			get
			{
				return this.GetTable<Busi_Annul_Turnover>();
			}
		}
		
		public System.Data.Linq.Table<Busi_Cust_Ref> Busi_Cust_Refs
		{
			get
			{
				return this.GetTable<Busi_Cust_Ref>();
			}
		}
		
		public System.Data.Linq.Table<Table> Tables
		{
			get
			{
				return this.GetTable<Table>();
			}
		}
		
		public System.Data.Linq.Table<VendorLogin> VendorLogins
		{
			get
			{
				return this.GetTable<VendorLogin>();
			}
		}
		
		public System.Data.Linq.Table<VendorRegistration> VendorRegistrations
		{
			get
			{
				return this.GetTable<VendorRegistration>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Busi_Annul_Turnover")]
	public partial class Busi_Annul_Turnover : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _VendorId;
		
		private System.Nullable<int> _Year1;
		
		private System.Nullable<int> _Year2;
		
		private System.Nullable<int> _Year3;
		
		private EntityRef<VendorRegistration> _VendorRegistration;
		
		private EntityRef<VendorRegistration> _VendorRegistration1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnVendorIdChanging(System.Nullable<int> value);
    partial void OnVendorIdChanged();
    partial void OnYear1Changing(System.Nullable<int> value);
    partial void OnYear1Changed();
    partial void OnYear2Changing(System.Nullable<int> value);
    partial void OnYear2Changed();
    partial void OnYear3Changing(System.Nullable<int> value);
    partial void OnYear3Changed();
    #endregion
		
		public Busi_Annul_Turnover()
		{
			this._VendorRegistration = default(EntityRef<VendorRegistration>);
			this._VendorRegistration1 = default(EntityRef<VendorRegistration>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorId", DbType="Int")]
		public System.Nullable<int> VendorId
		{
			get
			{
				return this._VendorId;
			}
			set
			{
				if ((this._VendorId != value))
				{
					if ((this._VendorRegistration.HasLoadedOrAssignedValue || this._VendorRegistration1.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnVendorIdChanging(value);
					this.SendPropertyChanging();
					this._VendorId = value;
					this.SendPropertyChanged("VendorId");
					this.OnVendorIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year1", DbType="Int")]
		public System.Nullable<int> Year1
		{
			get
			{
				return this._Year1;
			}
			set
			{
				if ((this._Year1 != value))
				{
					this.OnYear1Changing(value);
					this.SendPropertyChanging();
					this._Year1 = value;
					this.SendPropertyChanged("Year1");
					this.OnYear1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year2", DbType="Int")]
		public System.Nullable<int> Year2
		{
			get
			{
				return this._Year2;
			}
			set
			{
				if ((this._Year2 != value))
				{
					this.OnYear2Changing(value);
					this.SendPropertyChanging();
					this._Year2 = value;
					this.SendPropertyChanged("Year2");
					this.OnYear2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year3", DbType="Int")]
		public System.Nullable<int> Year3
		{
			get
			{
				return this._Year3;
			}
			set
			{
				if ((this._Year3 != value))
				{
					this.OnYear3Changing(value);
					this.SendPropertyChanging();
					this._Year3 = value;
					this.SendPropertyChanged("Year3");
					this.OnYear3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VendorRegistration_Busi_Annul_Turnover", Storage="_VendorRegistration", ThisKey="VendorId", OtherKey="ID", IsForeignKey=true)]
		public VendorRegistration VendorRegistration
		{
			get
			{
				return this._VendorRegistration.Entity;
			}
			set
			{
				VendorRegistration previousValue = this._VendorRegistration.Entity;
				if (((previousValue != value) 
							|| (this._VendorRegistration.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._VendorRegistration.Entity = null;
						previousValue.Busi_Annul_Turnovers.Remove(this);
					}
					this._VendorRegistration.Entity = value;
					if ((value != null))
					{
						value.Busi_Annul_Turnovers.Add(this);
						this._VendorId = value.ID;
					}
					else
					{
						this._VendorId = default(Nullable<int>);
					}
					this.SendPropertyChanged("VendorRegistration");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VendorRegistration_Busi_Annul_Turnover1", Storage="_VendorRegistration1", ThisKey="VendorId", OtherKey="ID", IsForeignKey=true)]
		public VendorRegistration VendorRegistration1
		{
			get
			{
				return this._VendorRegistration1.Entity;
			}
			set
			{
				VendorRegistration previousValue = this._VendorRegistration1.Entity;
				if (((previousValue != value) 
							|| (this._VendorRegistration1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._VendorRegistration1.Entity = null;
						previousValue.Busi_Annul_Turnovers1.Remove(this);
					}
					this._VendorRegistration1.Entity = value;
					if ((value != null))
					{
						value.Busi_Annul_Turnovers1.Add(this);
						this._VendorId = value.ID;
					}
					else
					{
						this._VendorId = default(Nullable<int>);
					}
					this.SendPropertyChanged("VendorRegistration1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Busi_Cust_Ref")]
	public partial class Busi_Cust_Ref : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _VendorID;
		
		private string _Customer_Name;
		
		private string _Location;
		
		private string _Contact_Person;
		
		private System.Data.Linq.Binary _Contact_Number;
		
		private EntityRef<VendorRegistration> _VendorRegistration;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnVendorIDChanging(System.Nullable<int> value);
    partial void OnVendorIDChanged();
    partial void OnCustomer_NameChanging(string value);
    partial void OnCustomer_NameChanged();
    partial void OnLocationChanging(string value);
    partial void OnLocationChanged();
    partial void OnContact_PersonChanging(string value);
    partial void OnContact_PersonChanged();
    partial void OnContact_NumberChanging(System.Data.Linq.Binary value);
    partial void OnContact_NumberChanged();
    #endregion
		
		public Busi_Cust_Ref()
		{
			this._VendorRegistration = default(EntityRef<VendorRegistration>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorID", DbType="Int")]
		public System.Nullable<int> VendorID
		{
			get
			{
				return this._VendorID;
			}
			set
			{
				if ((this._VendorID != value))
				{
					if (this._VendorRegistration.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnVendorIDChanging(value);
					this.SendPropertyChanging();
					this._VendorID = value;
					this.SendPropertyChanged("VendorID");
					this.OnVendorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Customer Name]", Storage="_Customer_Name", DbType="NVarChar(50)")]
		public string Customer_Name
		{
			get
			{
				return this._Customer_Name;
			}
			set
			{
				if ((this._Customer_Name != value))
				{
					this.OnCustomer_NameChanging(value);
					this.SendPropertyChanging();
					this._Customer_Name = value;
					this.SendPropertyChanged("Customer_Name");
					this.OnCustomer_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="VarChar(50)")]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this.OnLocationChanging(value);
					this.SendPropertyChanging();
					this._Location = value;
					this.SendPropertyChanged("Location");
					this.OnLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Contact Person]", Storage="_Contact_Person", DbType="NVarChar(50)")]
		public string Contact_Person
		{
			get
			{
				return this._Contact_Person;
			}
			set
			{
				if ((this._Contact_Person != value))
				{
					this.OnContact_PersonChanging(value);
					this.SendPropertyChanging();
					this._Contact_Person = value;
					this.SendPropertyChanged("Contact_Person");
					this.OnContact_PersonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Contact Number]", Storage="_Contact_Number", DbType="VarBinary(20)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Contact_Number
		{
			get
			{
				return this._Contact_Number;
			}
			set
			{
				if ((this._Contact_Number != value))
				{
					this.OnContact_NumberChanging(value);
					this.SendPropertyChanging();
					this._Contact_Number = value;
					this.SendPropertyChanged("Contact_Number");
					this.OnContact_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VendorRegistration_Busi_Cust_Ref", Storage="_VendorRegistration", ThisKey="VendorID", OtherKey="ID", IsForeignKey=true)]
		public VendorRegistration VendorRegistration
		{
			get
			{
				return this._VendorRegistration.Entity;
			}
			set
			{
				VendorRegistration previousValue = this._VendorRegistration.Entity;
				if (((previousValue != value) 
							|| (this._VendorRegistration.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._VendorRegistration.Entity = null;
						previousValue.Busi_Cust_Refs.Remove(this);
					}
					this._VendorRegistration.Entity = value;
					if ((value != null))
					{
						value.Busi_Cust_Refs.Add(this);
						this._VendorID = value.ID;
					}
					else
					{
						this._VendorID = default(Nullable<int>);
					}
					this.SendPropertyChanged("VendorRegistration");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Table]")]
	public partial class Table : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Free_Resource_;
		
		private string _Download;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnFree_Resource_Changing(string value);
    partial void OnFree_Resource_Changed();
    partial void OnDownloadChanging(string value);
    partial void OnDownloadChanged();
    #endregion
		
		public Table()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Free Resource ]", Storage="_Free_Resource_", DbType="VarChar(50)")]
		public string Free_Resource_
		{
			get
			{
				return this._Free_Resource_;
			}
			set
			{
				if ((this._Free_Resource_ != value))
				{
					this.OnFree_Resource_Changing(value);
					this.SendPropertyChanging();
					this._Free_Resource_ = value;
					this.SendPropertyChanged("Free_Resource_");
					this.OnFree_Resource_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Download", DbType="VarChar(50)")]
		public string Download
		{
			get
			{
				return this._Download;
			}
			set
			{
				if ((this._Download != value))
				{
					this.OnDownloadChanging(value);
					this.SendPropertyChanging();
					this._Download = value;
					this.SendPropertyChanged("Download");
					this.OnDownloadChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VendorLogin")]
	public partial class VendorLogin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _UserName;
		
		private int _Password;
		
		private string _NavUserName;
		
		private string _NavPassword;
		
		private int _TypeOfUser;
		
		private System.Nullable<bool> _ActiveUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPasswordChanging(int value);
    partial void OnPasswordChanged();
    partial void OnNavUserNameChanging(string value);
    partial void OnNavUserNameChanged();
    partial void OnNavPasswordChanging(string value);
    partial void OnNavPasswordChanged();
    partial void OnTypeOfUserChanging(int value);
    partial void OnTypeOfUserChanged();
    partial void OnActiveUserChanging(System.Nullable<bool> value);
    partial void OnActiveUserChanged();
    #endregion
		
		public VendorLogin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="Int NOT NULL")]
		public int Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NavUserName", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string NavUserName
		{
			get
			{
				return this._NavUserName;
			}
			set
			{
				if ((this._NavUserName != value))
				{
					this.OnNavUserNameChanging(value);
					this.SendPropertyChanging();
					this._NavUserName = value;
					this.SendPropertyChanged("NavUserName");
					this.OnNavUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NavPassword", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string NavPassword
		{
			get
			{
				return this._NavPassword;
			}
			set
			{
				if ((this._NavPassword != value))
				{
					this.OnNavPasswordChanging(value);
					this.SendPropertyChanging();
					this._NavPassword = value;
					this.SendPropertyChanged("NavPassword");
					this.OnNavPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeOfUser", DbType="Int NOT NULL")]
		public int TypeOfUser
		{
			get
			{
				return this._TypeOfUser;
			}
			set
			{
				if ((this._TypeOfUser != value))
				{
					this.OnTypeOfUserChanging(value);
					this.SendPropertyChanging();
					this._TypeOfUser = value;
					this.SendPropertyChanged("TypeOfUser");
					this.OnTypeOfUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActiveUser", DbType="Bit")]
		public System.Nullable<bool> ActiveUser
		{
			get
			{
				return this._ActiveUser;
			}
			set
			{
				if ((this._ActiveUser != value))
				{
					this.OnActiveUserChanging(value);
					this.SendPropertyChanging();
					this._ActiveUser = value;
					this.SendPropertyChanged("ActiveUser");
					this.OnActiveUserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VendorRegistration")]
	public partial class VendorRegistration : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _SourceRef;
		
		private int _TypeofBusi;
		
		private string _SourceRefInquiryBy;
		
		private string _SourceRefExternal;
		
		private string _SourceRefExternalOrgName;
		
		private string _SourceRefExternalContNo;
		
		private string _TypeofBusiForServiceProvider;
		
		private int _Title;
		
		private string _VendorName_HO;
		
		private string _PremisesNo_HO;
		
		private string _Address_1_HO;
		
		private string _Address_2_HO;
		
		private string _Address_3_HO;
		
		private string _City_HO;
		
		private string _StateRegion_HO;
		
		private System.Nullable<int> _PinCode_HO;
		
		private string _VendorName_WS;
		
		private string _PremisesNo_WS;
		
		private string _Address_1_WS;
		
		private string _Address_2_WS;
		
		private string _Address_3_WS;
		
		private string _City_WS;
		
		private string _StateRegion_WS;
		
		private System.Nullable<int> _PinCode_WS;
		
		private string _WebSite;
		
		private string _Con_PropDirPar_Name;
		
		private System.Nullable<int> _Con_PropDirPar_PhoneNo;
		
		private System.Nullable<int> _Con_PropDirPar_MobileNo;
		
		private string _Con_PropDirPar_EmailID;
		
		private string _Con_SalesDep_Name;
		
		private System.Nullable<int> _Con_SalesDep_PhoneNo;
		
		private System.Nullable<int> _Con_SalesDep_MobileNo;
		
		private string _Con_SalesDep_EmailID;
		
		private string _Con_AccDep_Name;
		
		private System.Nullable<int> _Con_AccDep_PhoneNo;
		
		private System.Nullable<int> _Con_AccDep_MobileNo;
		
		private string _Con_AccDep_EmailID;
		
		private string _PaymentTerm;
		
		private System.Nullable<int> _TotalStrengthOfManPower;
		
		private System.Nullable<int> _ShipmentTerm;
		
		private System.Nullable<int> _For_SOM_CSTNo;
		
		private System.Nullable<int> _For_SOM_VatNo;
		
		private string _For_SOM_PanNo;
		
		private string _For_SOM_TanNo;
		
		private System.Nullable<bool> _For_SOM_MicroSmallMediumEnterprise;
		
		private string _For_SOM_MSMERegNo;
		
		private string _For_SOM_RegisteredwithExcise;
		
		private string _For_SOM_ECCNo;
		
		private string _For_SOM_ExciseRange;
		
		private string _For_SOM_ExciseDivision;
		
		private string _For_SOM_ExciseCollectorate;
		
		private string _For_Others_PanNo;
		
		private string _For_Others_ServcieTaxRegNo;
		
		private string _For_Others_PFRegNo;
		
		private string _For_Others_ESIRegNo;
		
		private string _For_Others_ContractLicenseNo;
		
		private System.Nullable<bool> _For_Others_TDS_Applicability;
		
		private string _For_Others_LowerDeductionCertiNo;
		
		private string _BankName;
		
		private string _BankBrachName;
		
		private string _BankAccNo;
		
		private string _TypeofAcc;
		
		private string _IFSCode;
		
		private string _MICRCODE;
		
		private string _Bank_EmailID_UTR;
		
		private System.Nullable<int> _BankingMobileNo;
		
		private EntitySet<Busi_Annul_Turnover> _Busi_Annul_Turnovers;
		
		private EntitySet<Busi_Annul_Turnover> _Busi_Annul_Turnovers1;
		
		private EntitySet<Busi_Cust_Ref> _Busi_Cust_Refs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnSourceRefChanging(int value);
    partial void OnSourceRefChanged();
    partial void OnTypeofBusiChanging(int value);
    partial void OnTypeofBusiChanged();
    partial void OnSourceRefInquiryByChanging(string value);
    partial void OnSourceRefInquiryByChanged();
    partial void OnSourceRefExternalChanging(string value);
    partial void OnSourceRefExternalChanged();
    partial void OnSourceRefExternalOrgNameChanging(string value);
    partial void OnSourceRefExternalOrgNameChanged();
    partial void OnSourceRefExternalContNoChanging(string value);
    partial void OnSourceRefExternalContNoChanged();
    partial void OnTypeofBusiForServiceProviderChanging(string value);
    partial void OnTypeofBusiForServiceProviderChanged();
    partial void OnTitleChanging(int value);
    partial void OnTitleChanged();
    partial void OnVendorName_HOChanging(string value);
    partial void OnVendorName_HOChanged();
    partial void OnPremisesNo_HOChanging(string value);
    partial void OnPremisesNo_HOChanged();
    partial void OnAddress_1_HOChanging(string value);
    partial void OnAddress_1_HOChanged();
    partial void OnAddress_2_HOChanging(string value);
    partial void OnAddress_2_HOChanged();
    partial void OnAddress_3_HOChanging(string value);
    partial void OnAddress_3_HOChanged();
    partial void OnCity_HOChanging(string value);
    partial void OnCity_HOChanged();
    partial void OnStateRegion_HOChanging(string value);
    partial void OnStateRegion_HOChanged();
    partial void OnPinCode_HOChanging(System.Nullable<int> value);
    partial void OnPinCode_HOChanged();
    partial void OnVendorName_WSChanging(string value);
    partial void OnVendorName_WSChanged();
    partial void OnPremisesNo_WSChanging(string value);
    partial void OnPremisesNo_WSChanged();
    partial void OnAddress_1_WSChanging(string value);
    partial void OnAddress_1_WSChanged();
    partial void OnAddress_2_WSChanging(string value);
    partial void OnAddress_2_WSChanged();
    partial void OnAddress_3_WSChanging(string value);
    partial void OnAddress_3_WSChanged();
    partial void OnCity_WSChanging(string value);
    partial void OnCity_WSChanged();
    partial void OnStateRegion_WSChanging(string value);
    partial void OnStateRegion_WSChanged();
    partial void OnPinCode_WSChanging(System.Nullable<int> value);
    partial void OnPinCode_WSChanged();
    partial void OnWebSiteChanging(string value);
    partial void OnWebSiteChanged();
    partial void OnCon_PropDirPar_NameChanging(string value);
    partial void OnCon_PropDirPar_NameChanged();
    partial void OnCon_PropDirPar_PhoneNoChanging(System.Nullable<int> value);
    partial void OnCon_PropDirPar_PhoneNoChanged();
    partial void OnCon_PropDirPar_MobileNoChanging(System.Nullable<int> value);
    partial void OnCon_PropDirPar_MobileNoChanged();
    partial void OnCon_PropDirPar_EmailIDChanging(string value);
    partial void OnCon_PropDirPar_EmailIDChanged();
    partial void OnCon_SalesDep_NameChanging(string value);
    partial void OnCon_SalesDep_NameChanged();
    partial void OnCon_SalesDep_PhoneNoChanging(System.Nullable<int> value);
    partial void OnCon_SalesDep_PhoneNoChanged();
    partial void OnCon_SalesDep_MobileNoChanging(System.Nullable<int> value);
    partial void OnCon_SalesDep_MobileNoChanged();
    partial void OnCon_SalesDep_EmailIDChanging(string value);
    partial void OnCon_SalesDep_EmailIDChanged();
    partial void OnCon_AccDep_NameChanging(string value);
    partial void OnCon_AccDep_NameChanged();
    partial void OnCon_AccDep_PhoneNoChanging(System.Nullable<int> value);
    partial void OnCon_AccDep_PhoneNoChanged();
    partial void OnCon_AccDep_MobileNoChanging(System.Nullable<int> value);
    partial void OnCon_AccDep_MobileNoChanged();
    partial void OnCon_AccDep_EmailIDChanging(string value);
    partial void OnCon_AccDep_EmailIDChanged();
    partial void OnPaymentTermChanging(string value);
    partial void OnPaymentTermChanged();
    partial void OnTotalStrengthOfManPowerChanging(System.Nullable<int> value);
    partial void OnTotalStrengthOfManPowerChanged();
    partial void OnShipmentTermChanging(System.Nullable<int> value);
    partial void OnShipmentTermChanged();
    partial void OnFor_SOM_CSTNoChanging(System.Nullable<int> value);
    partial void OnFor_SOM_CSTNoChanged();
    partial void OnFor_SOM_VatNoChanging(System.Nullable<int> value);
    partial void OnFor_SOM_VatNoChanged();
    partial void OnFor_SOM_PanNoChanging(string value);
    partial void OnFor_SOM_PanNoChanged();
    partial void OnFor_SOM_TanNoChanging(string value);
    partial void OnFor_SOM_TanNoChanged();
    partial void OnFor_SOM_MicroSmallMediumEnterpriseChanging(System.Nullable<bool> value);
    partial void OnFor_SOM_MicroSmallMediumEnterpriseChanged();
    partial void OnFor_SOM_MSMERegNoChanging(string value);
    partial void OnFor_SOM_MSMERegNoChanged();
    partial void OnFor_SOM_RegisteredwithExciseChanging(string value);
    partial void OnFor_SOM_RegisteredwithExciseChanged();
    partial void OnFor_SOM_ECCNoChanging(string value);
    partial void OnFor_SOM_ECCNoChanged();
    partial void OnFor_SOM_ExciseRangeChanging(string value);
    partial void OnFor_SOM_ExciseRangeChanged();
    partial void OnFor_SOM_ExciseDivisionChanging(string value);
    partial void OnFor_SOM_ExciseDivisionChanged();
    partial void OnFor_SOM_ExciseCollectorateChanging(string value);
    partial void OnFor_SOM_ExciseCollectorateChanged();
    partial void OnFor_Others_PanNoChanging(string value);
    partial void OnFor_Others_PanNoChanged();
    partial void OnFor_Others_ServcieTaxRegNoChanging(string value);
    partial void OnFor_Others_ServcieTaxRegNoChanged();
    partial void OnFor_Others_PFRegNoChanging(string value);
    partial void OnFor_Others_PFRegNoChanged();
    partial void OnFor_Others_ESIRegNoChanging(string value);
    partial void OnFor_Others_ESIRegNoChanged();
    partial void OnFor_Others_ContractLicenseNoChanging(string value);
    partial void OnFor_Others_ContractLicenseNoChanged();
    partial void OnFor_Others_TDS_ApplicabilityChanging(System.Nullable<bool> value);
    partial void OnFor_Others_TDS_ApplicabilityChanged();
    partial void OnFor_Others_LowerDeductionCertiNoChanging(string value);
    partial void OnFor_Others_LowerDeductionCertiNoChanged();
    partial void OnBankNameChanging(string value);
    partial void OnBankNameChanged();
    partial void OnBankBrachNameChanging(string value);
    partial void OnBankBrachNameChanged();
    partial void OnBankAccNoChanging(string value);
    partial void OnBankAccNoChanged();
    partial void OnTypeofAccChanging(string value);
    partial void OnTypeofAccChanged();
    partial void OnIFSCodeChanging(string value);
    partial void OnIFSCodeChanged();
    partial void OnMICRCODEChanging(string value);
    partial void OnMICRCODEChanged();
    partial void OnBank_EmailID_UTRChanging(string value);
    partial void OnBank_EmailID_UTRChanged();
    partial void OnBankingMobileNoChanging(System.Nullable<int> value);
    partial void OnBankingMobileNoChanged();
    #endregion
		
		public VendorRegistration()
		{
			this._Busi_Annul_Turnovers = new EntitySet<Busi_Annul_Turnover>(new Action<Busi_Annul_Turnover>(this.attach_Busi_Annul_Turnovers), new Action<Busi_Annul_Turnover>(this.detach_Busi_Annul_Turnovers));
			this._Busi_Annul_Turnovers1 = new EntitySet<Busi_Annul_Turnover>(new Action<Busi_Annul_Turnover>(this.attach_Busi_Annul_Turnovers1), new Action<Busi_Annul_Turnover>(this.detach_Busi_Annul_Turnovers1));
			this._Busi_Cust_Refs = new EntitySet<Busi_Cust_Ref>(new Action<Busi_Cust_Ref>(this.attach_Busi_Cust_Refs), new Action<Busi_Cust_Ref>(this.detach_Busi_Cust_Refs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SourceRef", DbType="Int NOT NULL")]
		public int SourceRef
		{
			get
			{
				return this._SourceRef;
			}
			set
			{
				if ((this._SourceRef != value))
				{
					this.OnSourceRefChanging(value);
					this.SendPropertyChanging();
					this._SourceRef = value;
					this.SendPropertyChanged("SourceRef");
					this.OnSourceRefChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeofBusi", DbType="Int NOT NULL")]
		public int TypeofBusi
		{
			get
			{
				return this._TypeofBusi;
			}
			set
			{
				if ((this._TypeofBusi != value))
				{
					this.OnTypeofBusiChanging(value);
					this.SendPropertyChanging();
					this._TypeofBusi = value;
					this.SendPropertyChanged("TypeofBusi");
					this.OnTypeofBusiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SourceRefInquiryBy", DbType="VarChar(100)")]
		public string SourceRefInquiryBy
		{
			get
			{
				return this._SourceRefInquiryBy;
			}
			set
			{
				if ((this._SourceRefInquiryBy != value))
				{
					this.OnSourceRefInquiryByChanging(value);
					this.SendPropertyChanging();
					this._SourceRefInquiryBy = value;
					this.SendPropertyChanged("SourceRefInquiryBy");
					this.OnSourceRefInquiryByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SourceRefExternal", DbType="VarChar(100)")]
		public string SourceRefExternal
		{
			get
			{
				return this._SourceRefExternal;
			}
			set
			{
				if ((this._SourceRefExternal != value))
				{
					this.OnSourceRefExternalChanging(value);
					this.SendPropertyChanging();
					this._SourceRefExternal = value;
					this.SendPropertyChanged("SourceRefExternal");
					this.OnSourceRefExternalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SourceRefExternalOrgName", DbType="VarChar(250)")]
		public string SourceRefExternalOrgName
		{
			get
			{
				return this._SourceRefExternalOrgName;
			}
			set
			{
				if ((this._SourceRefExternalOrgName != value))
				{
					this.OnSourceRefExternalOrgNameChanging(value);
					this.SendPropertyChanging();
					this._SourceRefExternalOrgName = value;
					this.SendPropertyChanged("SourceRefExternalOrgName");
					this.OnSourceRefExternalOrgNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SourceRefExternalContNo", DbType="VarChar(20)")]
		public string SourceRefExternalContNo
		{
			get
			{
				return this._SourceRefExternalContNo;
			}
			set
			{
				if ((this._SourceRefExternalContNo != value))
				{
					this.OnSourceRefExternalContNoChanging(value);
					this.SendPropertyChanging();
					this._SourceRefExternalContNo = value;
					this.SendPropertyChanged("SourceRefExternalContNo");
					this.OnSourceRefExternalContNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeofBusiForServiceProvider", DbType="VarChar(250)")]
		public string TypeofBusiForServiceProvider
		{
			get
			{
				return this._TypeofBusiForServiceProvider;
			}
			set
			{
				if ((this._TypeofBusiForServiceProvider != value))
				{
					this.OnTypeofBusiForServiceProviderChanging(value);
					this.SendPropertyChanging();
					this._TypeofBusiForServiceProvider = value;
					this.SendPropertyChanged("TypeofBusiForServiceProvider");
					this.OnTypeofBusiForServiceProviderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="Int NOT NULL")]
		public int Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorName_HO", DbType="VarChar(250)")]
		public string VendorName_HO
		{
			get
			{
				return this._VendorName_HO;
			}
			set
			{
				if ((this._VendorName_HO != value))
				{
					this.OnVendorName_HOChanging(value);
					this.SendPropertyChanging();
					this._VendorName_HO = value;
					this.SendPropertyChanged("VendorName_HO");
					this.OnVendorName_HOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PremisesNo_HO", DbType="VarChar(250)")]
		public string PremisesNo_HO
		{
			get
			{
				return this._PremisesNo_HO;
			}
			set
			{
				if ((this._PremisesNo_HO != value))
				{
					this.OnPremisesNo_HOChanging(value);
					this.SendPropertyChanging();
					this._PremisesNo_HO = value;
					this.SendPropertyChanged("PremisesNo_HO");
					this.OnPremisesNo_HOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address_1_HO", DbType="VarChar(250)")]
		public string Address_1_HO
		{
			get
			{
				return this._Address_1_HO;
			}
			set
			{
				if ((this._Address_1_HO != value))
				{
					this.OnAddress_1_HOChanging(value);
					this.SendPropertyChanging();
					this._Address_1_HO = value;
					this.SendPropertyChanged("Address_1_HO");
					this.OnAddress_1_HOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address_2_HO", DbType="VarChar(250)")]
		public string Address_2_HO
		{
			get
			{
				return this._Address_2_HO;
			}
			set
			{
				if ((this._Address_2_HO != value))
				{
					this.OnAddress_2_HOChanging(value);
					this.SendPropertyChanging();
					this._Address_2_HO = value;
					this.SendPropertyChanged("Address_2_HO");
					this.OnAddress_2_HOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address_3_HO", DbType="VarChar(250)")]
		public string Address_3_HO
		{
			get
			{
				return this._Address_3_HO;
			}
			set
			{
				if ((this._Address_3_HO != value))
				{
					this.OnAddress_3_HOChanging(value);
					this.SendPropertyChanging();
					this._Address_3_HO = value;
					this.SendPropertyChanged("Address_3_HO");
					this.OnAddress_3_HOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City_HO", DbType="VarChar(250)")]
		public string City_HO
		{
			get
			{
				return this._City_HO;
			}
			set
			{
				if ((this._City_HO != value))
				{
					this.OnCity_HOChanging(value);
					this.SendPropertyChanging();
					this._City_HO = value;
					this.SendPropertyChanged("City_HO");
					this.OnCity_HOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StateRegion_HO", DbType="VarChar(250)")]
		public string StateRegion_HO
		{
			get
			{
				return this._StateRegion_HO;
			}
			set
			{
				if ((this._StateRegion_HO != value))
				{
					this.OnStateRegion_HOChanging(value);
					this.SendPropertyChanging();
					this._StateRegion_HO = value;
					this.SendPropertyChanged("StateRegion_HO");
					this.OnStateRegion_HOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PinCode_HO", DbType="Int")]
		public System.Nullable<int> PinCode_HO
		{
			get
			{
				return this._PinCode_HO;
			}
			set
			{
				if ((this._PinCode_HO != value))
				{
					this.OnPinCode_HOChanging(value);
					this.SendPropertyChanging();
					this._PinCode_HO = value;
					this.SendPropertyChanged("PinCode_HO");
					this.OnPinCode_HOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorName_WS", DbType="VarChar(250)")]
		public string VendorName_WS
		{
			get
			{
				return this._VendorName_WS;
			}
			set
			{
				if ((this._VendorName_WS != value))
				{
					this.OnVendorName_WSChanging(value);
					this.SendPropertyChanging();
					this._VendorName_WS = value;
					this.SendPropertyChanged("VendorName_WS");
					this.OnVendorName_WSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PremisesNo_WS", DbType="VarChar(250)")]
		public string PremisesNo_WS
		{
			get
			{
				return this._PremisesNo_WS;
			}
			set
			{
				if ((this._PremisesNo_WS != value))
				{
					this.OnPremisesNo_WSChanging(value);
					this.SendPropertyChanging();
					this._PremisesNo_WS = value;
					this.SendPropertyChanged("PremisesNo_WS");
					this.OnPremisesNo_WSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address_1_WS", DbType="VarChar(250)")]
		public string Address_1_WS
		{
			get
			{
				return this._Address_1_WS;
			}
			set
			{
				if ((this._Address_1_WS != value))
				{
					this.OnAddress_1_WSChanging(value);
					this.SendPropertyChanging();
					this._Address_1_WS = value;
					this.SendPropertyChanged("Address_1_WS");
					this.OnAddress_1_WSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address_2_WS", DbType="VarChar(250)")]
		public string Address_2_WS
		{
			get
			{
				return this._Address_2_WS;
			}
			set
			{
				if ((this._Address_2_WS != value))
				{
					this.OnAddress_2_WSChanging(value);
					this.SendPropertyChanging();
					this._Address_2_WS = value;
					this.SendPropertyChanged("Address_2_WS");
					this.OnAddress_2_WSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address_3_WS", DbType="VarChar(250)")]
		public string Address_3_WS
		{
			get
			{
				return this._Address_3_WS;
			}
			set
			{
				if ((this._Address_3_WS != value))
				{
					this.OnAddress_3_WSChanging(value);
					this.SendPropertyChanging();
					this._Address_3_WS = value;
					this.SendPropertyChanged("Address_3_WS");
					this.OnAddress_3_WSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City_WS", DbType="VarChar(250)")]
		public string City_WS
		{
			get
			{
				return this._City_WS;
			}
			set
			{
				if ((this._City_WS != value))
				{
					this.OnCity_WSChanging(value);
					this.SendPropertyChanging();
					this._City_WS = value;
					this.SendPropertyChanged("City_WS");
					this.OnCity_WSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StateRegion_WS", DbType="VarChar(250)")]
		public string StateRegion_WS
		{
			get
			{
				return this._StateRegion_WS;
			}
			set
			{
				if ((this._StateRegion_WS != value))
				{
					this.OnStateRegion_WSChanging(value);
					this.SendPropertyChanging();
					this._StateRegion_WS = value;
					this.SendPropertyChanged("StateRegion_WS");
					this.OnStateRegion_WSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PinCode_WS", DbType="Int")]
		public System.Nullable<int> PinCode_WS
		{
			get
			{
				return this._PinCode_WS;
			}
			set
			{
				if ((this._PinCode_WS != value))
				{
					this.OnPinCode_WSChanging(value);
					this.SendPropertyChanging();
					this._PinCode_WS = value;
					this.SendPropertyChanged("PinCode_WS");
					this.OnPinCode_WSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebSite", DbType="VarChar(250)")]
		public string WebSite
		{
			get
			{
				return this._WebSite;
			}
			set
			{
				if ((this._WebSite != value))
				{
					this.OnWebSiteChanging(value);
					this.SendPropertyChanging();
					this._WebSite = value;
					this.SendPropertyChanged("WebSite");
					this.OnWebSiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Con_PropDirPar_Name", DbType="VarChar(250)")]
		public string Con_PropDirPar_Name
		{
			get
			{
				return this._Con_PropDirPar_Name;
			}
			set
			{
				if ((this._Con_PropDirPar_Name != value))
				{
					this.OnCon_PropDirPar_NameChanging(value);
					this.SendPropertyChanging();
					this._Con_PropDirPar_Name = value;
					this.SendPropertyChanged("Con_PropDirPar_Name");
					this.OnCon_PropDirPar_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Con_PropDirPar_PhoneNo", DbType="Int")]
		public System.Nullable<int> Con_PropDirPar_PhoneNo
		{
			get
			{
				return this._Con_PropDirPar_PhoneNo;
			}
			set
			{
				if ((this._Con_PropDirPar_PhoneNo != value))
				{
					this.OnCon_PropDirPar_PhoneNoChanging(value);
					this.SendPropertyChanging();
					this._Con_PropDirPar_PhoneNo = value;
					this.SendPropertyChanged("Con_PropDirPar_PhoneNo");
					this.OnCon_PropDirPar_PhoneNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Con_PropDirPar_MobileNo", DbType="Int")]
		public System.Nullable<int> Con_PropDirPar_MobileNo
		{
			get
			{
				return this._Con_PropDirPar_MobileNo;
			}
			set
			{
				if ((this._Con_PropDirPar_MobileNo != value))
				{
					this.OnCon_PropDirPar_MobileNoChanging(value);
					this.SendPropertyChanging();
					this._Con_PropDirPar_MobileNo = value;
					this.SendPropertyChanged("Con_PropDirPar_MobileNo");
					this.OnCon_PropDirPar_MobileNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Con_PropDirPar_EmailID", DbType="VarChar(250)")]
		public string Con_PropDirPar_EmailID
		{
			get
			{
				return this._Con_PropDirPar_EmailID;
			}
			set
			{
				if ((this._Con_PropDirPar_EmailID != value))
				{
					this.OnCon_PropDirPar_EmailIDChanging(value);
					this.SendPropertyChanging();
					this._Con_PropDirPar_EmailID = value;
					this.SendPropertyChanged("Con_PropDirPar_EmailID");
					this.OnCon_PropDirPar_EmailIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Con_SalesDep_Name", DbType="VarChar(250)")]
		public string Con_SalesDep_Name
		{
			get
			{
				return this._Con_SalesDep_Name;
			}
			set
			{
				if ((this._Con_SalesDep_Name != value))
				{
					this.OnCon_SalesDep_NameChanging(value);
					this.SendPropertyChanging();
					this._Con_SalesDep_Name = value;
					this.SendPropertyChanged("Con_SalesDep_Name");
					this.OnCon_SalesDep_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Con_SalesDep_PhoneNo", DbType="Int")]
		public System.Nullable<int> Con_SalesDep_PhoneNo
		{
			get
			{
				return this._Con_SalesDep_PhoneNo;
			}
			set
			{
				if ((this._Con_SalesDep_PhoneNo != value))
				{
					this.OnCon_SalesDep_PhoneNoChanging(value);
					this.SendPropertyChanging();
					this._Con_SalesDep_PhoneNo = value;
					this.SendPropertyChanged("Con_SalesDep_PhoneNo");
					this.OnCon_SalesDep_PhoneNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Con_SalesDep_MobileNo", DbType="Int")]
		public System.Nullable<int> Con_SalesDep_MobileNo
		{
			get
			{
				return this._Con_SalesDep_MobileNo;
			}
			set
			{
				if ((this._Con_SalesDep_MobileNo != value))
				{
					this.OnCon_SalesDep_MobileNoChanging(value);
					this.SendPropertyChanging();
					this._Con_SalesDep_MobileNo = value;
					this.SendPropertyChanged("Con_SalesDep_MobileNo");
					this.OnCon_SalesDep_MobileNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Con_SalesDep_EmailID", DbType="VarChar(250)")]
		public string Con_SalesDep_EmailID
		{
			get
			{
				return this._Con_SalesDep_EmailID;
			}
			set
			{
				if ((this._Con_SalesDep_EmailID != value))
				{
					this.OnCon_SalesDep_EmailIDChanging(value);
					this.SendPropertyChanging();
					this._Con_SalesDep_EmailID = value;
					this.SendPropertyChanged("Con_SalesDep_EmailID");
					this.OnCon_SalesDep_EmailIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Con_AccDep_Name", DbType="VarChar(250)")]
		public string Con_AccDep_Name
		{
			get
			{
				return this._Con_AccDep_Name;
			}
			set
			{
				if ((this._Con_AccDep_Name != value))
				{
					this.OnCon_AccDep_NameChanging(value);
					this.SendPropertyChanging();
					this._Con_AccDep_Name = value;
					this.SendPropertyChanged("Con_AccDep_Name");
					this.OnCon_AccDep_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Con_AccDep_PhoneNo", DbType="Int")]
		public System.Nullable<int> Con_AccDep_PhoneNo
		{
			get
			{
				return this._Con_AccDep_PhoneNo;
			}
			set
			{
				if ((this._Con_AccDep_PhoneNo != value))
				{
					this.OnCon_AccDep_PhoneNoChanging(value);
					this.SendPropertyChanging();
					this._Con_AccDep_PhoneNo = value;
					this.SendPropertyChanged("Con_AccDep_PhoneNo");
					this.OnCon_AccDep_PhoneNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Con_AccDep_MobileNo", DbType="Int")]
		public System.Nullable<int> Con_AccDep_MobileNo
		{
			get
			{
				return this._Con_AccDep_MobileNo;
			}
			set
			{
				if ((this._Con_AccDep_MobileNo != value))
				{
					this.OnCon_AccDep_MobileNoChanging(value);
					this.SendPropertyChanging();
					this._Con_AccDep_MobileNo = value;
					this.SendPropertyChanged("Con_AccDep_MobileNo");
					this.OnCon_AccDep_MobileNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Con_AccDep_EmailID", DbType="VarChar(250)")]
		public string Con_AccDep_EmailID
		{
			get
			{
				return this._Con_AccDep_EmailID;
			}
			set
			{
				if ((this._Con_AccDep_EmailID != value))
				{
					this.OnCon_AccDep_EmailIDChanging(value);
					this.SendPropertyChanging();
					this._Con_AccDep_EmailID = value;
					this.SendPropertyChanged("Con_AccDep_EmailID");
					this.OnCon_AccDep_EmailIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentTerm", DbType="VarChar(250)")]
		public string PaymentTerm
		{
			get
			{
				return this._PaymentTerm;
			}
			set
			{
				if ((this._PaymentTerm != value))
				{
					this.OnPaymentTermChanging(value);
					this.SendPropertyChanging();
					this._PaymentTerm = value;
					this.SendPropertyChanged("PaymentTerm");
					this.OnPaymentTermChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalStrengthOfManPower", DbType="Int")]
		public System.Nullable<int> TotalStrengthOfManPower
		{
			get
			{
				return this._TotalStrengthOfManPower;
			}
			set
			{
				if ((this._TotalStrengthOfManPower != value))
				{
					this.OnTotalStrengthOfManPowerChanging(value);
					this.SendPropertyChanging();
					this._TotalStrengthOfManPower = value;
					this.SendPropertyChanged("TotalStrengthOfManPower");
					this.OnTotalStrengthOfManPowerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipmentTerm", DbType="Int")]
		public System.Nullable<int> ShipmentTerm
		{
			get
			{
				return this._ShipmentTerm;
			}
			set
			{
				if ((this._ShipmentTerm != value))
				{
					this.OnShipmentTermChanging(value);
					this.SendPropertyChanging();
					this._ShipmentTerm = value;
					this.SendPropertyChanged("ShipmentTerm");
					this.OnShipmentTermChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_For_SOM_CSTNo", DbType="Int")]
		public System.Nullable<int> For_SOM_CSTNo
		{
			get
			{
				return this._For_SOM_CSTNo;
			}
			set
			{
				if ((this._For_SOM_CSTNo != value))
				{
					this.OnFor_SOM_CSTNoChanging(value);
					this.SendPropertyChanging();
					this._For_SOM_CSTNo = value;
					this.SendPropertyChanged("For_SOM_CSTNo");
					this.OnFor_SOM_CSTNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_For_SOM_VatNo", DbType="Int")]
		public System.Nullable<int> For_SOM_VatNo
		{
			get
			{
				return this._For_SOM_VatNo;
			}
			set
			{
				if ((this._For_SOM_VatNo != value))
				{
					this.OnFor_SOM_VatNoChanging(value);
					this.SendPropertyChanging();
					this._For_SOM_VatNo = value;
					this.SendPropertyChanged("For_SOM_VatNo");
					this.OnFor_SOM_VatNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_For_SOM_PanNo", DbType="VarChar(12)")]
		public string For_SOM_PanNo
		{
			get
			{
				return this._For_SOM_PanNo;
			}
			set
			{
				if ((this._For_SOM_PanNo != value))
				{
					this.OnFor_SOM_PanNoChanging(value);
					this.SendPropertyChanging();
					this._For_SOM_PanNo = value;
					this.SendPropertyChanged("For_SOM_PanNo");
					this.OnFor_SOM_PanNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_For_SOM_TanNo", DbType="VarChar(20)")]
		public string For_SOM_TanNo
		{
			get
			{
				return this._For_SOM_TanNo;
			}
			set
			{
				if ((this._For_SOM_TanNo != value))
				{
					this.OnFor_SOM_TanNoChanging(value);
					this.SendPropertyChanging();
					this._For_SOM_TanNo = value;
					this.SendPropertyChanged("For_SOM_TanNo");
					this.OnFor_SOM_TanNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_For_SOM_MicroSmallMediumEnterprise", DbType="Bit")]
		public System.Nullable<bool> For_SOM_MicroSmallMediumEnterprise
		{
			get
			{
				return this._For_SOM_MicroSmallMediumEnterprise;
			}
			set
			{
				if ((this._For_SOM_MicroSmallMediumEnterprise != value))
				{
					this.OnFor_SOM_MicroSmallMediumEnterpriseChanging(value);
					this.SendPropertyChanging();
					this._For_SOM_MicroSmallMediumEnterprise = value;
					this.SendPropertyChanged("For_SOM_MicroSmallMediumEnterprise");
					this.OnFor_SOM_MicroSmallMediumEnterpriseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_For_SOM_MSMERegNo", DbType="VarChar(250)")]
		public string For_SOM_MSMERegNo
		{
			get
			{
				return this._For_SOM_MSMERegNo;
			}
			set
			{
				if ((this._For_SOM_MSMERegNo != value))
				{
					this.OnFor_SOM_MSMERegNoChanging(value);
					this.SendPropertyChanging();
					this._For_SOM_MSMERegNo = value;
					this.SendPropertyChanged("For_SOM_MSMERegNo");
					this.OnFor_SOM_MSMERegNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_For_SOM_RegisteredwithExcise", DbType="VarChar(250)")]
		public string For_SOM_RegisteredwithExcise
		{
			get
			{
				return this._For_SOM_RegisteredwithExcise;
			}
			set
			{
				if ((this._For_SOM_RegisteredwithExcise != value))
				{
					this.OnFor_SOM_RegisteredwithExciseChanging(value);
					this.SendPropertyChanging();
					this._For_SOM_RegisteredwithExcise = value;
					this.SendPropertyChanged("For_SOM_RegisteredwithExcise");
					this.OnFor_SOM_RegisteredwithExciseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_For_SOM_ECCNo", DbType="VarChar(250)")]
		public string For_SOM_ECCNo
		{
			get
			{
				return this._For_SOM_ECCNo;
			}
			set
			{
				if ((this._For_SOM_ECCNo != value))
				{
					this.OnFor_SOM_ECCNoChanging(value);
					this.SendPropertyChanging();
					this._For_SOM_ECCNo = value;
					this.SendPropertyChanged("For_SOM_ECCNo");
					this.OnFor_SOM_ECCNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_For_SOM_ExciseRange", DbType="VarChar(250)")]
		public string For_SOM_ExciseRange
		{
			get
			{
				return this._For_SOM_ExciseRange;
			}
			set
			{
				if ((this._For_SOM_ExciseRange != value))
				{
					this.OnFor_SOM_ExciseRangeChanging(value);
					this.SendPropertyChanging();
					this._For_SOM_ExciseRange = value;
					this.SendPropertyChanged("For_SOM_ExciseRange");
					this.OnFor_SOM_ExciseRangeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_For_SOM_ExciseDivision", DbType="VarChar(250)")]
		public string For_SOM_ExciseDivision
		{
			get
			{
				return this._For_SOM_ExciseDivision;
			}
			set
			{
				if ((this._For_SOM_ExciseDivision != value))
				{
					this.OnFor_SOM_ExciseDivisionChanging(value);
					this.SendPropertyChanging();
					this._For_SOM_ExciseDivision = value;
					this.SendPropertyChanged("For_SOM_ExciseDivision");
					this.OnFor_SOM_ExciseDivisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_For_SOM_ExciseCollectorate", DbType="VarChar(250)")]
		public string For_SOM_ExciseCollectorate
		{
			get
			{
				return this._For_SOM_ExciseCollectorate;
			}
			set
			{
				if ((this._For_SOM_ExciseCollectorate != value))
				{
					this.OnFor_SOM_ExciseCollectorateChanging(value);
					this.SendPropertyChanging();
					this._For_SOM_ExciseCollectorate = value;
					this.SendPropertyChanged("For_SOM_ExciseCollectorate");
					this.OnFor_SOM_ExciseCollectorateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_For_Others_PanNo", DbType="VarChar(50)")]
		public string For_Others_PanNo
		{
			get
			{
				return this._For_Others_PanNo;
			}
			set
			{
				if ((this._For_Others_PanNo != value))
				{
					this.OnFor_Others_PanNoChanging(value);
					this.SendPropertyChanging();
					this._For_Others_PanNo = value;
					this.SendPropertyChanged("For_Others_PanNo");
					this.OnFor_Others_PanNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_For_Others_ServcieTaxRegNo", DbType="VarChar(50)")]
		public string For_Others_ServcieTaxRegNo
		{
			get
			{
				return this._For_Others_ServcieTaxRegNo;
			}
			set
			{
				if ((this._For_Others_ServcieTaxRegNo != value))
				{
					this.OnFor_Others_ServcieTaxRegNoChanging(value);
					this.SendPropertyChanging();
					this._For_Others_ServcieTaxRegNo = value;
					this.SendPropertyChanged("For_Others_ServcieTaxRegNo");
					this.OnFor_Others_ServcieTaxRegNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_For_Others_PFRegNo", DbType="VarChar(50)")]
		public string For_Others_PFRegNo
		{
			get
			{
				return this._For_Others_PFRegNo;
			}
			set
			{
				if ((this._For_Others_PFRegNo != value))
				{
					this.OnFor_Others_PFRegNoChanging(value);
					this.SendPropertyChanging();
					this._For_Others_PFRegNo = value;
					this.SendPropertyChanged("For_Others_PFRegNo");
					this.OnFor_Others_PFRegNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_For_Others_ESIRegNo", DbType="VarChar(250)")]
		public string For_Others_ESIRegNo
		{
			get
			{
				return this._For_Others_ESIRegNo;
			}
			set
			{
				if ((this._For_Others_ESIRegNo != value))
				{
					this.OnFor_Others_ESIRegNoChanging(value);
					this.SendPropertyChanging();
					this._For_Others_ESIRegNo = value;
					this.SendPropertyChanged("For_Others_ESIRegNo");
					this.OnFor_Others_ESIRegNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_For_Others_ContractLicenseNo", DbType="VarChar(250)")]
		public string For_Others_ContractLicenseNo
		{
			get
			{
				return this._For_Others_ContractLicenseNo;
			}
			set
			{
				if ((this._For_Others_ContractLicenseNo != value))
				{
					this.OnFor_Others_ContractLicenseNoChanging(value);
					this.SendPropertyChanging();
					this._For_Others_ContractLicenseNo = value;
					this.SendPropertyChanged("For_Others_ContractLicenseNo");
					this.OnFor_Others_ContractLicenseNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_For_Others_TDS_Applicability", DbType="Bit")]
		public System.Nullable<bool> For_Others_TDS_Applicability
		{
			get
			{
				return this._For_Others_TDS_Applicability;
			}
			set
			{
				if ((this._For_Others_TDS_Applicability != value))
				{
					this.OnFor_Others_TDS_ApplicabilityChanging(value);
					this.SendPropertyChanging();
					this._For_Others_TDS_Applicability = value;
					this.SendPropertyChanged("For_Others_TDS_Applicability");
					this.OnFor_Others_TDS_ApplicabilityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_For_Others_LowerDeductionCertiNo", DbType="VarChar(50)")]
		public string For_Others_LowerDeductionCertiNo
		{
			get
			{
				return this._For_Others_LowerDeductionCertiNo;
			}
			set
			{
				if ((this._For_Others_LowerDeductionCertiNo != value))
				{
					this.OnFor_Others_LowerDeductionCertiNoChanging(value);
					this.SendPropertyChanging();
					this._For_Others_LowerDeductionCertiNo = value;
					this.SendPropertyChanged("For_Others_LowerDeductionCertiNo");
					this.OnFor_Others_LowerDeductionCertiNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankName", DbType="VarChar(250)")]
		public string BankName
		{
			get
			{
				return this._BankName;
			}
			set
			{
				if ((this._BankName != value))
				{
					this.OnBankNameChanging(value);
					this.SendPropertyChanging();
					this._BankName = value;
					this.SendPropertyChanged("BankName");
					this.OnBankNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankBrachName", DbType="VarChar(250)")]
		public string BankBrachName
		{
			get
			{
				return this._BankBrachName;
			}
			set
			{
				if ((this._BankBrachName != value))
				{
					this.OnBankBrachNameChanging(value);
					this.SendPropertyChanging();
					this._BankBrachName = value;
					this.SendPropertyChanged("BankBrachName");
					this.OnBankBrachNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankAccNo", DbType="VarChar(50)")]
		public string BankAccNo
		{
			get
			{
				return this._BankAccNo;
			}
			set
			{
				if ((this._BankAccNo != value))
				{
					this.OnBankAccNoChanging(value);
					this.SendPropertyChanging();
					this._BankAccNo = value;
					this.SendPropertyChanged("BankAccNo");
					this.OnBankAccNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeofAcc", DbType="VarChar(50)")]
		public string TypeofAcc
		{
			get
			{
				return this._TypeofAcc;
			}
			set
			{
				if ((this._TypeofAcc != value))
				{
					this.OnTypeofAccChanging(value);
					this.SendPropertyChanging();
					this._TypeofAcc = value;
					this.SendPropertyChanged("TypeofAcc");
					this.OnTypeofAccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IFSCode", DbType="VarChar(11)")]
		public string IFSCode
		{
			get
			{
				return this._IFSCode;
			}
			set
			{
				if ((this._IFSCode != value))
				{
					this.OnIFSCodeChanging(value);
					this.SendPropertyChanging();
					this._IFSCode = value;
					this.SendPropertyChanged("IFSCode");
					this.OnIFSCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MICRCODE", DbType="VarChar(9)")]
		public string MICRCODE
		{
			get
			{
				return this._MICRCODE;
			}
			set
			{
				if ((this._MICRCODE != value))
				{
					this.OnMICRCODEChanging(value);
					this.SendPropertyChanging();
					this._MICRCODE = value;
					this.SendPropertyChanged("MICRCODE");
					this.OnMICRCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bank_EmailID_UTR", DbType="VarChar(50)")]
		public string Bank_EmailID_UTR
		{
			get
			{
				return this._Bank_EmailID_UTR;
			}
			set
			{
				if ((this._Bank_EmailID_UTR != value))
				{
					this.OnBank_EmailID_UTRChanging(value);
					this.SendPropertyChanging();
					this._Bank_EmailID_UTR = value;
					this.SendPropertyChanged("Bank_EmailID_UTR");
					this.OnBank_EmailID_UTRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankingMobileNo", DbType="Int")]
		public System.Nullable<int> BankingMobileNo
		{
			get
			{
				return this._BankingMobileNo;
			}
			set
			{
				if ((this._BankingMobileNo != value))
				{
					this.OnBankingMobileNoChanging(value);
					this.SendPropertyChanging();
					this._BankingMobileNo = value;
					this.SendPropertyChanged("BankingMobileNo");
					this.OnBankingMobileNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VendorRegistration_Busi_Annul_Turnover", Storage="_Busi_Annul_Turnovers", ThisKey="ID", OtherKey="VendorId")]
		public EntitySet<Busi_Annul_Turnover> Busi_Annul_Turnovers
		{
			get
			{
				return this._Busi_Annul_Turnovers;
			}
			set
			{
				this._Busi_Annul_Turnovers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VendorRegistration_Busi_Annul_Turnover1", Storage="_Busi_Annul_Turnovers1", ThisKey="ID", OtherKey="VendorId")]
		public EntitySet<Busi_Annul_Turnover> Busi_Annul_Turnovers1
		{
			get
			{
				return this._Busi_Annul_Turnovers1;
			}
			set
			{
				this._Busi_Annul_Turnovers1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VendorRegistration_Busi_Cust_Ref", Storage="_Busi_Cust_Refs", ThisKey="ID", OtherKey="VendorID")]
		public EntitySet<Busi_Cust_Ref> Busi_Cust_Refs
		{
			get
			{
				return this._Busi_Cust_Refs;
			}
			set
			{
				this._Busi_Cust_Refs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Busi_Annul_Turnovers(Busi_Annul_Turnover entity)
		{
			this.SendPropertyChanging();
			entity.VendorRegistration = this;
		}
		
		private void detach_Busi_Annul_Turnovers(Busi_Annul_Turnover entity)
		{
			this.SendPropertyChanging();
			entity.VendorRegistration = null;
		}
		
		private void attach_Busi_Annul_Turnovers1(Busi_Annul_Turnover entity)
		{
			this.SendPropertyChanging();
			entity.VendorRegistration1 = this;
		}
		
		private void detach_Busi_Annul_Turnovers1(Busi_Annul_Turnover entity)
		{
			this.SendPropertyChanging();
			entity.VendorRegistration1 = null;
		}
		
		private void attach_Busi_Cust_Refs(Busi_Cust_Ref entity)
		{
			this.SendPropertyChanging();
			entity.VendorRegistration = this;
		}
		
		private void detach_Busi_Cust_Refs(Busi_Cust_Ref entity)
		{
			this.SendPropertyChanging();
			entity.VendorRegistration = null;
		}
	}
}
#pragma warning restore 1591
